"""
CISA-sourced APT & Threat Actor Database
Basado en alertas oficiales de CISA, MITRE ATT&CK y reportes públicos de inteligencia.
"""
from __future__ import annotations
import re

CISA_APT_DATABASE: list[dict] = [
    # ── RUSIA ─────────────────────────────────────────────────────────────────
    {
        "name": "APT28",
        "aliases": ["Fancy Bear", "Pawn Storm", "STRONTIUM", "Forest Blizzard", "Sofacy", "Sednit", "Tsar Team"],
        "country": "Russia",
        "sponsor": "GRU (Unidad 26165 / 74455)",
        "motivation": "Espionaje político-militar, operaciones de desinformación",
        "risk_level": "Critical",
        "target_sectors": ["Gobierno", "Defensa", "ONG", "Think Tanks", "Medios", "Aeroespacial"],
        "target_regions": ["Europa Occidental", "EEUU", "LATAM", "OTAN"],
        "known_campaigns": ["Operation Pawn Storm", "Sednit Campaign", "Olympic Destroyer 2018", "DNC Hack 2016", "Macron Hack 2017"],
        "typical_malware": ["X-Agent", "Sofacy", "Zebrocy", "Drovorub", "LoJax"],
        "typical_ttps": ["T1566.001 - Spearphishing Attachment", "T1078 - Valid Accounts", "T1027 - Obfuscated Files", "T1190 - Exploit Public-Facing Application"],
        "mitre_group_id": "G0007",
        "cisa_advisories": ["AA20-239A", "AA22-074A", "AA23-108A"],
        "description": "Grupo APT ruso del GRU activo desde 2004. Especializado en robo de datos políticos e interferencia electoral.",
    },
    {
        "name": "APT29",
        "aliases": ["Cozy Bear", "Midnight Blizzard", "NOBELIUM", "The Dukes", "UNC2452", "Dark Halo"],
        "country": "Russia",
        "sponsor": "SVR (Servicio de Inteligencia Exterior)",
        "motivation": "Espionaje estratégico de largo plazo, robo de inteligencia gubernamental",
        "risk_level": "Critical",
        "target_sectors": ["Gobierno", "Think Tanks", "ONG", "Tecnología", "Salud", "Diplomatico"],
        "target_regions": ["EEUU", "Europa", "OTAN", "Global"],
        "known_campaigns": ["SolarWinds SUNBURST 2020", "DNC Hack 2015", "COVID-19 Vaccine Theft", "Microsoft Teams Phishing 2023", "TeamViewer Breach 2024"],
        "typical_malware": ["SUNBURST", "TEARDROP", "Cobalt Strike", "MiniDuke", "CosmicDuke", "WellMess"],
        "typical_ttps": ["T1195.002 - Compromise Software Supply Chain", "T1550.001 - OAuth Tokens", "T1071.001 - Web Protocols C2", "T1584 - Compromise Infrastructure"],
        "mitre_group_id": "G0016",
        "cisa_advisories": ["AA21-116A", "AA23-347A", "AA24-057A"],
        "description": "Grupo APT ruso del SVR. Operaciones de espionaje persistente y sigilosas. Responsables del ataque a SolarWinds.",
    },
    {
        "name": "Sandworm",
        "aliases": ["Voodoo Bear", "IRIDIUM", "Seashell Blizzard", "BlackEnergy Group", "TeleBots"],
        "country": "Russia",
        "sponsor": "GRU (Unidad 74455)",
        "motivation": "Sabotaje de infraestructura crítica, ataques destructivos",
        "risk_level": "Critical",
        "target_sectors": ["Energía", "Telecomunicaciones", "Gobierno", "Transporte", "Defensa"],
        "target_regions": ["Ucrania", "Europa", "EEUU", "Global"],
        "known_campaigns": ["NotPetya 2017", "Ukraine Power Grid 2015/2016", "Olympic Destroyer 2018", "Viasat Hack 2022", "Industroyer2 2022"],
        "typical_malware": ["NotPetya", "Industroyer", "BlackEnergy", "Cyclops Blink", "CaddyWiper"],
        "typical_ttps": ["T1485 - Data Destruction", "T1561 - Disk Wipe", "T1498 - Network DoS", "T1059.005 - Visual Basic"],
        "mitre_group_id": "G0034",
        "cisa_advisories": ["AA22-076A", "AA22-110A", "AA20-020A"],
        "description": "El grupo de APT más destructivo de Rusia. Responsable de NotPetya y ataques a infraestructura eléctrica de Ucrania.",
    },
    {
        "name": "Turla",
        "aliases": ["Snake", "Uroburos", "Waterbug", "VENOMOUS BEAR", "Secret Blizzard", "KRYPTON"],
        "country": "Russia",
        "sponsor": "FSB (Servicio Federal de Seguridad)",
        "motivation": "Espionaje de larga duración, robo de inteligencia diplomática",
        "risk_level": "High",
        "target_sectors": ["Gobierno", "Diplomático", "Defensa", "Investigación"],
        "target_regions": ["Europa Oriental", "Oriente Medio", "Asia Central"],
        "known_campaigns": ["Operation Epic", "Neuron/Nautilus Campaign", "Hijacking OilRig infrastructure"],
        "typical_malware": ["Snake/Uroburos", "KopiLuwak", "Meterpreter", "HyperStack", "Gazer"],
        "typical_ttps": ["T1071.003 - Mail Protocols", "T1090.003 - Multi-hop Proxy", "T1584 - Compromise Infrastructure"],
        "mitre_group_id": "G0010",
        "cisa_advisories": ["AA23-129A"],
        "description": "Grupo FSB ruso ultra-sofisticado. Famoso por infectar servidores de otros APTs para usar su infraestructura.",
    },
    {
        "name": "Gamaredon",
        "aliases": ["Primitive Bear", "Armageddon", "ACTINIUM", "Shuckworm", "Aqua Blizzard"],
        "country": "Russia",
        "sponsor": "FSB / SBU (operativo desde Crimea)",
        "motivation": "Espionaje contra Ucrania, recolección masiva de inteligencia",
        "risk_level": "High",
        "target_sectors": ["Gobierno Ucraniano", "Defensa", "Fuerzas de Seguridad"],
        "target_regions": ["Ucrania", "Europa Oriental"],
        "known_campaigns": ["Operation Armageddon", "Phishing Campaigns Ukraine 2021-2024"],
        "typical_malware": ["Pterodo/Pteranodon", "GammaLoad", "QuietSieve"],
        "typical_ttps": ["T1566.001 - Spearphishing", "T1059.001 - PowerShell", "T1105 - Ingress Tool Transfer"],
        "mitre_group_id": "G0047",
        "cisa_advisories": ["AA22-011A"],
        "description": "APT ruso focalizado exclusivamente en Ucrania. Opera desde territorio ocupado de Crimea.",
    },
    # ── CHINA ─────────────────────────────────────────────────────────────────
    {
        "name": "APT1",
        "aliases": ["Comment Crew", "Comment Group", "Shanghai Group"],
        "country": "China",
        "sponsor": "PLA (Unidad 61398)",
        "motivation": "Espionaje industrial y robo de propiedad intelectual",
        "risk_level": "High",
        "target_sectors": ["Aeroespacial", "Defensa", "Energía", "Telecomunicaciones", "Tecnología"],
        "target_regions": ["EEUU", "Canadá", "Reino Unido"],
        "known_campaigns": ["APT1 Operations 2006-2013", "Comment Crew Intrusions"],
        "typical_malware": ["WEBC2", "BISCUIT", "GlooxMail", "MaCroMaIL"],
        "typical_ttps": ["T1566 - Phishing", "T1059 - Command Line Interface", "T1078 - Valid Accounts"],
        "mitre_group_id": "G0006",
        "cisa_advisories": [],
        "description": "Grupo del PLA chino. Expuesto por Mandiant en 2013. Responsable del robo de TBs de propiedad intelectual.",
    },
    {
        "name": "APT10",
        "aliases": ["Stone Panda", "MenuPass", "CVNX", "Red Apollo", "POTASSIUM", "Cicada"],
        "country": "China",
        "sponsor": "MSS (Ministerio de Seguridad del Estado)",
        "motivation": "Espionaje industrial a través de proveedores de servicios administrados (MSP)",
        "risk_level": "Critical",
        "target_sectors": ["MSP/IT", "Gobierno", "Salud", "Telecomunicaciones", "Manufactura"],
        "target_regions": ["EEUU", "Japón", "Europa", "LATAM", "Global"],
        "known_campaigns": ["Operation Cloud Hopper", "Operation Soft Cell"],
        "typical_malware": ["PlugX", "QuasarRAT", "RedLeaves", "ChChes", "UPPERCUT"],
        "typical_ttps": ["T1199 - Trusted Relationship", "T1078 - Valid Accounts MSP", "T1021.001 - RDP"],
        "mitre_group_id": "G0045",
        "cisa_advisories": ["AA21-048A"],
        "description": "MSS chino. Especializado en comprometer MSPs para acceder a sus clientes downstream. Operation Cloud Hopper afectó a docenas de países.",
    },
    {
        "name": "APT40",
        "aliases": ["TEMP.Periscope", "Bronze Mohawk", "Kryptonite Panda", "GADOLINIUM", "Leviathan"],
        "country": "China",
        "sponsor": "MSS (Hainan State Security Department)",
        "motivation": "Espionaje marítimo, robo de secretos navales y de defensa",
        "risk_level": "Critical",
        "target_sectors": ["Naval/Marítimo", "Defensa", "Aviación", "Gobierno", "Investigación"],
        "target_regions": ["Mar del Sur de China", "EEUU", "Australia", "Europa"],
        "known_campaigns": ["Operation Ghostwriter", "Campaign Against Naval Research", "Pulse Secure VPN Exploitation 2021"],
        "typical_malware": ["AIRBREAK", "MURKYTOP", "HOMEFRY", "LUNCHMONEY"],
        "typical_ttps": ["T1190 - Exploit VPN", "T1133 - External Remote Services", "T1078 - Valid Accounts"],
        "mitre_group_id": "G0065",
        "cisa_advisories": ["AA21-200A"],
        "description": "MSS de Hainan. Focalizado en inteligencia naval y marítima. Explotó Pulse Secure VPN en 2021.",
    },
    {
        "name": "APT41",
        "aliases": ["Double Dragon", "Winnti Group", "Barium", "Wicked Panda", "Bronze Atlas"],
        "country": "China",
        "sponsor": "MSS (operaciones duales: espionaje + crimen financiero)",
        "motivation": "Espionaje estatal Y ganancias financieras mediante ransomware/criptomonedas",
        "risk_level": "Critical",
        "target_sectors": ["Videojuegos", "Salud", "Telecomunicaciones", "Tecnología", "Finanzas"],
        "target_regions": ["Global - 30+ países"],
        "known_campaigns": ["ShadowPad Campaign", "Healthcare Targeting COVID-19", "Supply Chain via Asus/CCleaner"],
        "typical_malware": ["ShadowPad", "Winnti", "POISONPLUG", "KEYPLUG", "CROSSWALK"],
        "typical_ttps": ["T1195 - Supply Chain Compromise", "T1059.003 - Windows Command Shell", "T1027 - Obfuscation"],
        "mitre_group_id": "G0096",
        "cisa_advisories": [],
        "description": "Único grupo APT que combina espionaje estatal con operaciones de crimen cibernético para beneficio propio.",
    },
    {
        "name": "Volt Typhoon",
        "aliases": ["BRONZE SILHOUETTE", "Vanguard Panda", "Dev-0391", "UNC3236"],
        "country": "China",
        "sponsor": "PLA / MSS",
        "motivation": "Pre-posicionamiento en infraestructura crítica de EEUU para conflicto potencial con Taiwán",
        "risk_level": "Critical",
        "target_sectors": ["Energía", "Agua", "Transporte", "Telecomunicaciones", "Puertos"],
        "target_regions": ["EEUU", "Guam", "Pacífico"],
        "known_campaigns": ["Living off the Land US Infrastructure 2021-2024", "Guam Telecom Operations"],
        "typical_malware": ["KV-botnet", "Web Shells", "Living-off-the-land binaries (LOLBins)"],
        "typical_ttps": ["T1078 - Valid Accounts", "T1505.003 - Web Shell", "T1036 - Masquerading", "T1562 - Impair Defenses"],
        "mitre_group_id": "G1017",
        "cisa_advisories": ["AA23-144A", "AA24-038A"],
        "description": "Pre-posicionamiento sigiloso en infraestructura crítica de EEUU. Usa técnicas Living-off-the-Land para evadir detección.",
    },
    {
        "name": "Salt Typhoon",
        "aliases": ["Earth Estries", "FamousSparrow", "GhostEmperor", "UNC2286"],
        "country": "China",
        "sponsor": "MSS",
        "motivation": "Intercepción de comunicaciones de inteligencia en telecos de EEUU",
        "risk_level": "Critical",
        "target_sectors": ["Telecomunicaciones", "ISP", "Gobierno", "Defensa"],
        "target_regions": ["EEUU", "Asia-Pacífico"],
        "known_campaigns": ["US Telecom Breach 2024 (AT&T, Verizon, T-Mobile)", "Lumen Compromise"],
        "typical_malware": ["SparrowDoor", "ShadowPad", "Demodex rootkit"],
        "typical_ttps": ["T1040 - Network Sniffing", "T1078 - Valid Accounts", "T1133 - External Remote Services"],
        "mitre_group_id": "G1043",
        "cisa_advisories": ["AA24-038A"],
        "description": "Comprometió las principales telecos de EEUU en 2024 para interceptar comunicaciones sensibles del gobierno.",
    },
    {
        "name": "Hafnium",
        "aliases": ["HAFNIUM", "Silk Typhoon"],
        "country": "China",
        "sponsor": "MSS",
        "motivation": "Robo de información de investigadores, think tanks, instituciones de defensa",
        "risk_level": "Critical",
        "target_sectors": ["Investigación Infecciosas", "Think Tanks", "Defensa", "ONG", "Abogacía"],
        "target_regions": ["EEUU", "Global"],
        "known_campaigns": ["Microsoft Exchange Server Zero-Days 2021 (ProxyLogon)"],
        "typical_malware": ["China Chopper Webshell", "ASPXSPY", "Cobalt Strike"],
        "typical_ttps": ["T1190 - Exploit Public-Facing Application", "T1505.003 - Web Shell", "T1560 - Archive Collected Data"],
        "mitre_group_id": "G0125",
        "cisa_advisories": ["AA21-062A"],
        "description": "Responsable de la explotación masiva de ProxyLogon en Exchange Server afectando 250,000+ servidores globalmente.",
    },
    # ── IRÁN ──────────────────────────────────────────────────────────────────
    {
        "name": "APT33",
        "aliases": ["Elfin", "Refined Kitten", "Magnallium", "HOLMIUM"],
        "country": "Iran",
        "sponsor": "IRGC (Cuerpo de la Guardia Revolucionaria Islámica)",
        "motivation": "Sabotaje de sector energético, espionaje contra Arabia Saudita y aliados",
        "risk_level": "High",
        "target_sectors": ["Petroquímica", "Aviación", "Energía", "Defensa"],
        "target_regions": ["Arabia Saudita", "EEUU", "Europa", "Corea del Sur"],
        "known_campaigns": ["Operation Elfin", "Targeting Aviation Sector 2020"],
        "typical_malware": ["SHAMOON 3", "DropShot", "StoneDrill", "TURNEDUP", "NANOCORE"],
        "typical_ttps": ["T1566 - Phishing", "T1489 - Service Stop", "T1485 - Data Destruction"],
        "mitre_group_id": "G0064",
        "cisa_advisories": [],
        "description": "IRGC iraní focalizado en sector energético y aviación de la región del Golfo Pérsico.",
    },
    {
        "name": "APT34",
        "aliases": ["OilRig", "Helix Kitten", "Chrysene", "IRN2", "EUROPIUM", "Hazel Sandstorm"],
        "country": "Iran",
        "sponsor": "MOIS (Ministerio de Inteligencia y Seguridad)",
        "motivation": "Espionaje contra países vecinos, robo de credenciales gubernamentales",
        "risk_level": "High",
        "target_sectors": ["Gobierno", "Financiero", "Energía", "Telecomunicaciones", "Químico"],
        "target_regions": ["Oriente Medio", "EEUU", "Europa"],
        "known_campaigns": ["Operation OilRig", "DNSpionage 2018", "SideTwist Campaign"],
        "typical_malware": ["POWRUNER", "BONDUPDATER", "QUADAGENT", "RDAT", "Saitama"],
        "typical_ttps": ["T1071.004 - DNS C2", "T1566 - Phishing", "T1059.001 - PowerShell"],
        "mitre_group_id": "G0049",
        "cisa_advisories": ["AA24-241A"],
        "description": "MOIS iraní activo desde 2014. Experto en tunneling de C2 por DNS. Apunta principalmente al Oriente Medio.",
    },
    {
        "name": "APT35",
        "aliases": ["Charming Kitten", "Phosphorus", "TA453", "Mint Sandstorm", "Yellow Garuda"],
        "country": "Iran",
        "sponsor": "IRGC (Islamic Revolutionary Guard Corps)",
        "motivation": "Espionaje contra disidentes iraníes, periodistas, académicos y think tanks",
        "risk_level": "High",
        "target_sectors": ["Academia", "Think Tanks", "Periodismo", "ONG", "Gobierno", "Salud"],
        "target_regions": ["EEUU", "Israel", "Europa", "Global"],
        "known_campaigns": ["BadBlood Operation", "COVID Vaccine Research Targeting", "Google Credential Harvesting"],
        "typical_malware": ["POWERSTAR", "CharmPower", "GRAMDOOR", "MEDIAPL"],
        "typical_ttps": ["T1566.002 - Spearphishing Link", "T1078 - Valid Accounts", "T1539 - Steal Web Session Cookie"],
        "mitre_group_id": "G0059",
        "cisa_advisories": ["AA22-264A"],
        "description": "IRGC iraní especializado en ingeniería social sofisticada. Usa identidades falsas de expertos para ganar confianza de víctimas.",
    },
    {
        "name": "MuddyWater",
        "aliases": ["MERCURY", "Static Kitten", "Seedworm", "TA450", "Mango Sandstorm"],
        "country": "Iran",
        "sponsor": "MOIS",
        "motivation": "Vigilancia de disidentes y espionaje regional",
        "risk_level": "High",
        "target_sectors": ["Gobierno", "Telecomunicaciones", "Defensa", "Petróleo y Gas"],
        "target_regions": ["Oriente Medio", "Asia Central", "Europa", "EEUU"],
        "known_campaigns": ["Outer Space Campaign", "Small Sieve Campaign 2022"],
        "typical_malware": ["POWERSTATS", "SHARPSTATS", "Small Sieve", "SloughRAT"],
        "typical_ttps": ["T1059.001 - PowerShell", "T1566.001 - Spearphishing", "T1105 - Tool Transfer"],
        "mitre_group_id": "G0069",
        "cisa_advisories": ["AA22-055A"],
        "description": "Subgrupo del MOIS iraní activo desde 2017. Opera frecuentemente en Oriente Medio y apunta a telecomunicaciones.",
    },
    # ── COREA DEL NORTE ───────────────────────────────────────────────────────
    {
        "name": "Lazarus Group",
        "aliases": ["HIDDEN COBRA", "Whois Team", "Zinc", "Diamond Sleet", "Labyrinth Chollima", "UNC577"],
        "country": "North Korea",
        "sponsor": "RGB (Oficina General de Reconocimiento)",
        "motivation": "Robo financiero para financiar programa nuclear, sabotaje y espionaje",
        "risk_level": "Critical",
        "target_sectors": ["Finanzas/Cripto", "Defensa", "Gobierno", "Medios", "Manufactura"],
        "target_regions": ["Global - especialmente EEUU, Europa, LATAM, Asia"],
        "known_campaigns": ["Sony Pictures Hack 2014", "Bangladesh Bank Heist 2016 ($81M)", "WannaCry 2017", "Bybit Hack 2025 ($1.5B)"],
        "typical_malware": ["ELECTRICFISH", "BADCALL", "AppleJeus", "DTrack", "BLINDINGCAN"],
        "typical_ttps": ["T1566 - Phishing", "T1203 - Exploitation", "T1041 - Exfiltration C2", "T1583 - Acquire Infrastructure"],
        "mitre_group_id": "G0032",
        "cisa_advisories": ["AA22-108A", "AA21-048A", "AA20-239B"],
        "description": "El grupo APT más peligroso de Corea del Norte. Responsable de +$3B en robos cripto y múltiples ataques destructivos.",
    },
    {
        "name": "APT38",
        "aliases": ["BeagleBoyz", "Stardust Chollima", "Bluenoroff"],
        "country": "North Korea",
        "sponsor": "RGB",
        "motivation": "Robo financiero del sistema bancario internacional (SWIFT)",
        "risk_level": "Critical",
        "target_sectors": ["Banca", "Finanzas", "Criptomonedas"],
        "target_regions": ["Asia-Pacífico", "África", "LATAM", "Europa"],
        "known_campaigns": ["FASTCash ATM Heists", "SWIFT Attacks 2015-2019", "Bangladesh Bank"],
        "typical_malware": ["ECCENTRICBANDWAGON", "VIVACIOUSGIFT", "ARTFULPIE", "HOPLIGHT"],
        "typical_ttps": ["T1072 - Software Deployment Tools", "T1565.001 - Stored Data Manipulation", "T1486 - Ransom"],
        "mitre_group_id": "G0082",
        "cisa_advisories": ["AA20-239B"],
        "description": "Subgrupo de Lazarus especializado en ataques SWIFT. Responsable de los mayores robos bancarios de la historia.",
    },
    {
        "name": "Kimsuky",
        "aliases": ["Velvet Chollima", "Black Banshee", "Thallium", "Emerald Sleet", "TA406"],
        "country": "North Korea",
        "sponsor": "RGB",
        "motivation": "Recolección de inteligencia geopolítica, espionaje sobre política norcoreana",
        "risk_level": "High",
        "target_sectors": ["Think Tanks", "Academia", "Gobierno", "Defensa", "Medios"],
        "target_regions": ["Corea del Sur", "EEUU", "Japón", "Europa"],
        "known_campaigns": ["Operation Kimsuky", "STOLEN PENCIL Campaign", "ReconShark 2023"],
        "typical_malware": ["BabyShark", "ReconShark", "RandomQuery", "AppleSeed"],
        "typical_ttps": ["T1566 - Spearphishing", "T1598 - Phishing for Information", "T1059.005 - VBS"],
        "mitre_group_id": "G0094",
        "cisa_advisories": ["AA20-301A", "AA23-059A"],
        "description": "RGB focalizado en recolección de inteligencia sobre política hacia Corea del Norte. Muy activo contra think tanks y académicos.",
    },
    {
        "name": "Andariel",
        "aliases": ["Silent Chollima", "Stonefly", "Onyx Sleet", "DarkSeoul"],
        "country": "North Korea",
        "sponsor": "RGB (Lazarus subgroup)",
        "motivation": "Ciberespionaje, ransomware financiero y sabotaje",
        "risk_level": "High",
        "target_sectors": ["Defensa", "Salud", "Manufactura", "Finanzas", "Gobierno"],
        "target_regions": ["Corea del Sur", "EEUU", "Japón", "Global"],
        "known_campaigns": ["Maui Ransomware Healthcare 2021-2022", "DEV-0530 Operations"],
        "typical_malware": ["Maui Ransomware", "Dtrack", "SHATTEREDGLASS", "MagicRAT"],
        "typical_ttps": ["T1486 - Ransomware Encryption", "T1190 - VPN Exploitation", "T1059 - Scripting"],
        "mitre_group_id": "G0138",
        "cisa_advisories": ["AA22-187A"],
        "description": "Subgrupo de Lazarus especializado en ransomware contra sector salud de EEUU para financiar operaciones.",
    },
    # ── GRUPOS CRIMINALES ─────────────────────────────────────────────────────
    {
        "name": "LockBit",
        "aliases": ["LockBit 3.0", "LockBit Black", "LockBit 2.0", "ABCD"],
        "country": "Rusia/Internacional",
        "sponsor": "Criminal (RaaS - Ransomware as a Service)",
        "motivation": "Extorsión financiera mediante ransomware",
        "risk_level": "Critical",
        "target_sectors": ["Todos los sectores (indiscriminado)", "Salud", "Gobierno", "Manufactura"],
        "target_regions": ["Global"],
        "known_campaigns": ["ICBC Attack 2023", "Boeing Breach 2023", "Royal Mail UK 2023", "ION Trading 2023"],
        "typical_malware": ["LockBit 3.0", "StealBit", "Cobalt Strike"],
        "typical_ttps": ["T1486 - Data Encryption", "T1490 - Inhibit Recovery", "T1567.002 - Exfiltration to Cloud"],
        "mitre_group_id": "G0075",
        "cisa_advisories": ["AA23-075A", "AA23-165A"],
        "description": "El grupo de ransomware más prolífico de la historia. Opera como RaaS con 100+ afiliados. Infraestructura parcialmente desmantelada en 2024.",
    },
    {
        "name": "ALPHV/BlackCat",
        "aliases": ["BlackCat", "Noberus", "UNC4466"],
        "country": "Rusia/Internacional",
        "sponsor": "Criminal (RaaS)",
        "motivation": "Extorsión triple: cifrado + exfiltración + acoso a víctimas",
        "risk_level": "Critical",
        "target_sectors": ["Salud", "Infraestructura Crítica", "Manufactura", "Gobierno"],
        "target_regions": ["EEUU", "Europa", "Global"],
        "known_campaigns": ["MGM Resorts 2023", "Change Healthcare 2024 ($22M pagado)", "Caesars Entertainment 2023"],
        "typical_malware": ["BlackCat/ALPHV ransomware", "ExMatter", "Conti-related tools"],
        "typical_ttps": ["T1486 - Data Encryption", "T1083 - File/Directory Discovery", "T1190 - Exploit Public-Facing App"],
        "mitre_group_id": "G1006",
        "cisa_advisories": ["AA23-353A"],
        "description": "RaaS basado en Rust con capacidades cross-platform. El ataque a Change Healthcare afectó al 30% del sector salud de EEUU.",
    },
    {
        "name": "Cl0p",
        "aliases": ["TA505", "GOLD TAHOE", "Lace Tempest"],
        "country": "Ucrania/Rusia",
        "sponsor": "Criminal",
        "motivation": "Extorsión masiva mediante zero-days en software de transferencia de archivos",
        "risk_level": "Critical",
        "target_sectors": ["Financiero", "Manufactura", "Educación", "Gobierno", "Salud"],
        "target_regions": ["Global"],
        "known_campaigns": ["MOVEit Zero-Day 2023 (2,600+ organizaciones)", "GoAnywhere Zero-Day 2023", "Accellion FTA 2020"],
        "typical_malware": ["Cl0p Ransomware", "DEWMODE", "FlawedAmmyy", "SDBOT"],
        "typical_ttps": ["T1190 - Zero-Day Exploits", "T1567.002 - Exfiltration to Cloud", "T1486 - Data Encryption"],
        "mitre_group_id": "G0092",
        "cisa_advisories": ["AA23-165A"],
        "description": "Especialista en zero-days de software de transferencia masiva de archivos. MOVEit les hizo el grupo más impactante de 2023.",
    },
    {
        "name": "Conti",
        "aliases": ["WIZARD SPIDER", "Gold Ulrick", "ITG23"],
        "country": "Rusia",
        "sponsor": "Criminal (RaaS)",
        "motivation": "Extorsión financiera, ahora disuelto pero fragmentado en subgrupos",
        "risk_level": "High",
        "target_sectors": ["Gobierno", "Salud", "Manufactura", "Telecomunicaciones"],
        "target_regions": ["Global - especialmente EEUU e Irlanda"],
        "known_campaigns": ["Ireland HSE Attack 2021", "Costa Rica Government 2022", "Conti Leaks 2022"],
        "typical_malware": ["Conti Ransomware", "TrickBot", "BazarLoader", "Cobalt Strike"],
        "typical_ttps": ["T1486 - Ransomware", "T1078 - Valid Accounts", "T1021.002 - SMB/Admin Shares"],
        "mitre_group_id": "G0102",
        "cisa_advisories": ["AA21-265A"],
        "description": "Ransomware ruso disuelto en 2022 tras filtraciones. Sus miembros formaron grupos como Royal, Black Basta, ALPHV.",
    },
    {
        "name": "Play Ransomware",
        "aliases": ["PlayCrypt", "Fiddling Scorpius"],
        "country": "Internacional",
        "sponsor": "Criminal",
        "motivation": "Extorsión doble mediante cifrado y exfiltración",
        "risk_level": "High",
        "target_sectors": ["Gobierno Municipal", "Telecomunicaciones", "Manufactura", "Salud"],
        "target_regions": ["EEUU", "Europa", "LATAM"],
        "known_campaigns": ["City of Oakland 2023", "Arnold Clark UK 2022", "Córdoba Judicial Argentina 2022"],
        "typical_malware": ["Play Ransomware", "Cobalt Strike", "SystemBC"],
        "typical_ttps": ["T1190 - Exploit FortiOS/Exchange", "T1486 - Data Encryption", "T1083 - Discovery"],
        "mitre_group_id": "G1040",
        "cisa_advisories": ["AA23-352A"],
        "description": "Grupo ransomware activo en LATAM. Atacó al Poder Judicial de Córdoba (Argentina) y múltiples gobiernos municipales de EEUU.",
    },
    # ── LATAM / REGIONALES ────────────────────────────────────────────────────
    {
        "name": "Blind Eagle",
        "aliases": ["APT-C-36", "AguilaCiega"],
        "country": "Colombia/Sur América",
        "sponsor": "No atribuido oficialmente (posiblemente mercenario o estado)",
        "motivation": "Espionaje contra entidades gubernamentales y financieras de Colombia y Ecuador",
        "risk_level": "High",
        "target_sectors": ["Gobierno", "Financiero", "Salud", "Policía Nacional"],
        "target_regions": ["Colombia", "Ecuador", "Chile", "España"],
        "known_campaigns": ["Operation Blind Eagle 2019-2024", "Ataque Policía Nacional Colombia 2023"],
        "typical_malware": ["AsyncRAT", "BitRAT", "Remcos RAT", "njRAT", "QuasarRAT"],
        "typical_ttps": ["T1566.001 - Spearphishing PDF", "T1059.001 - PowerShell", "T1027 - Obfuscation"],
        "mitre_group_id": "G0099",
        "cisa_advisories": [],
        "description": "El APT más activo en Colombia. Sus víctimas incluyen entidades del gobierno colombiano, sector financiero y judicial.",
    },
    {
        "name": "Machete",
        "aliases": ["El Machete", "APT-Q-48"],
        "country": "Sur América (Venezuela)",
        "sponsor": "Posiblemente estatal venezolano",
        "motivation": "Espionaje militar y político en América Latina",
        "risk_level": "Medium",
        "target_sectors": ["Fuerzas Militares", "Gobierno", "Diplomático"],
        "target_regions": ["Venezuela", "Ecuador", "Colombia", "Nicaragua", "Cuba"],
        "known_campaigns": ["Operation Machete 2010-2024"],
        "typical_malware": ["Machete Spy Tool", "Python RAT personalizado"],
        "typical_ttps": ["T1566.001 - Spearphishing", "T1113 - Screen Capture", "T1125 - Video Capture"],
        "mitre_group_id": "G0095",
        "cisa_advisories": [],
        "description": "Grupo de espionaje activo en LATAM desde 2010. Focalizado en militares y diplomáticos de la región.",
    },
    {
        "name": "Guacamaya",
        "aliases": ["Guacamaya Leaks"],
        "country": "América Latina",
        "sponsor": "Hacktivista",
        "motivation": "Transparencia y activismo político contra gobiernos y multinacionales",
        "risk_level": "Medium",
        "target_sectors": ["Fuerzas Militares", "Policía", "Minería/Extractivas", "Gobierno"],
        "target_regions": ["Chile", "Colombia", "México", "El Salvador", "Perú"],
        "known_campaigns": ["EMCO Chile Hack 2022", "FFAA Colombia 2022", "Ejército Mexico SEDENA 2022"],
        "typical_malware": ["ProxyShell", "Herramientas Open Source"],
        "typical_ttps": ["T1190 - ProxyShell/Exchange", "T1119 - Automated Collection", "T1048 - Exfiltration Alt Protocol"],
        "mitre_group_id": None,
        "cisa_advisories": [],
        "description": "Hacktivistas latinoamericanos. Filtraron millones de documentos militares en LATAM en 2022.",
    },
    # ── OTROS GRUPOS SIGNIFICATIVOS ───────────────────────────────────────────
    {
        "name": "Scattered Spider",
        "aliases": ["UNC3944", "ROASTED 0KTAPUS", "Scatter Swine", "Muddled Libra"],
        "country": "EEUU/Reino Unido (jóvenes angloparlantes)",
        "sponsor": "Criminal",
        "motivation": "Extorsión financiera, robo de datos, SIM swapping",
        "risk_level": "Critical",
        "target_sectors": ["Telecomunicaciones", "Hospitalidad", "Finanzas", "Retail"],
        "target_regions": ["EEUU", "Reino Unido", "Canadá"],
        "known_campaigns": ["MGM Resorts 2023", "Caesars 2023", "0ktapus Campaign 2022 (130+ organizaciones)"],
        "typical_malware": ["XTUNNEL", "Cobalt Strike", "ScreenConnect", "AnyDesk"],
        "typical_ttps": ["T1621 - MFA Fatigue", "T1566 - Smishing/Vishing", "T1199 - Trusted Relationship"],
        "mitre_group_id": "G1015",
        "cisa_advisories": ["AA23-320A"],
        "description": "Jóvenes angloparlantes (Gen Z) con habilidades avanzadas de ingeniería social. Derrotaron las defensas de MGM en horas.",
    },
    {
        "name": "FIN7",
        "aliases": ["Carbon Spider", "Sangria Tempest", "ELBRUS", "ITG14"],
        "country": "Rusia/Ucrania",
        "sponsor": "Criminal",
        "motivation": "Robo financiero de sector retail y hospitality, ransomware",
        "risk_level": "High",
        "target_sectors": ["Retail", "Restaurantes", "Hospitalidad", "Financiero"],
        "target_regions": ["EEUU", "Europa", "Global"],
        "known_campaigns": ["CARBANAK Campaign", "Clop partnership", "Darkside/BlackMatter links"],
        "typical_malware": ["Carbanak", "GRIFFON", "BOOSTWRITE", "REvil (distribuidor)"],
        "typical_ttps": ["T1566.001 - Spearphishing", "T1071.001 - HTTP C2", "T1113 - Screen Capture"],
        "mitre_group_id": "G0046",
        "cisa_advisories": ["AA22-277A"],
        "description": "Grupo criminal-espía ruso responsable de robo de +$1B a instituciones financieras. Ahora distribuye ransomware.",
    },
    {
        "name": "Killnet",
        "aliases": ["KillNet", "Anonymous Russia"],
        "country": "Russia",
        "sponsor": "Pro-ruso (hacktivista con vínculos GRU no confirmados)",
        "motivation": "Propaganda y ataques DDoS contra países que apoyan a Ucrania",
        "risk_level": "Medium",
        "target_sectors": ["Gobierno", "Infraestructura Crítica", "Salud", "Aviación"],
        "target_regions": ["Europa Occidental", "EEUU", "OTAN"],
        "known_campaigns": ["DDoS NATO Countries 2022-2024", "US Healthcare DDoS 2023"],
        "typical_malware": ["Herramientas DDoS personalizadas", "Mirai botnets"],
        "typical_ttps": ["T1498 - Network DoS", "T1499 - Endpoint DoS", "T1583 - Botnet"],
        "mitre_group_id": None,
        "cisa_advisories": ["AA22-110A"],
        "description": "Hacktivistas pro-rusos especializados en DDoS. Coordinan ataques a través de Telegram contra países de la OTAN.",
    },
]


def match_actor_to_database(actor_name: str, database: list[dict] | None = None) -> dict | None:
    """Fuzzy match an actor name against the CISA database.
    Returns the first matching entry or None.
    """
    if database is None:
        database = CISA_APT_DATABASE

    name_lower = actor_name.lower().strip()

    for entry in database:
        # Exact match on canonical name
        if entry["name"].lower() == name_lower:
            return entry
        # Match on any alias
        for alias in entry.get("aliases", []):
            if alias.lower() == name_lower:
                return entry
        # Partial match: actor_name contained in name or alias
        if name_lower in entry["name"].lower() or entry["name"].lower() in name_lower:
            return entry
        for alias in entry.get("aliases", []):
            if name_lower in alias.lower() or alias.lower() in name_lower:
                return entry

    return None


def get_actors_by_country(country: str) -> list[dict]:
    return [a for a in CISA_APT_DATABASE if country.lower() in a["country"].lower()]


def get_actors_by_sector(sector: str) -> list[dict]:
    sector_lower = sector.lower()
    return [
        a for a in CISA_APT_DATABASE
        if any(sector_lower in s.lower() for s in a.get("target_sectors", []))
    ]


def get_full_database() -> list[dict]:
    return CISA_APT_DATABASE
